/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import classes.*;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author Max
 */
public class GamePanel extends javax.swing.JPanel implements ActionListener {

    private Timer timer;
    private Game game;
    private Input input;
    private Connection connection;
    
    /**
     * Creates new form GamePanel
     */
    public GamePanel() {
        initComponents();
        
        //panels
        pnlRules.setVisible(false);
        
        //game objects
        input = new Input(this);
        addMouseListener(input);
        connection = new Connection();
        game = new Game(this, input, connection);
        timer = new Timer(16, this);
        timer.start();
    }
    
    public LoginPanel getLogin() {
        return pnlLogin;
    }
    
    public RulesPanel getRules() {
        return pnlRules;
    }

    @Override
    public void paintComponent(Graphics g) {
        super.paintComponent(g);
        Graphics2D g2d = (Graphics2D) g;
        game.draw(g2d);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlLogin = new frames.LoginPanel();
        pnlRules = new frames.RulesPanel();
        pnlCardSelect2 = new frames.pnlCardSelect();

        setPreferredSize(new java.awt.Dimension(1200, 675));
        setLayout(null);
        add(pnlLogin);
        pnlLogin.setBounds(440, 220, 376, 242);
        add(pnlRules);
        pnlRules.setBounds(360, 160, 527, 329);
        add(pnlCardSelect2);
        pnlCardSelect2.setBounds(250, 140, 779, 468);
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void actionPerformed(ActionEvent e) {
        input.update();
        game.update();
        repaint();
    }
    
    public void sendExit() {
        connection.sendExit();
    }
    
    public void connect(String server, int port, String user, String pass) {
        boolean[] collection = Loader.loadCollection(user, pass);
        if (collection == null) {
            JOptionPane.showMessageDialog(this,
                    "Failed to connect to DB.\nEither the DB is down or the username/password is incorrect.");
            return;
        }
        else {
            game.setCollection(collection);
        }
        if (connection.connect(server, port))
            pnlLogin.setVisible(false);
        else
            JOptionPane.showMessageDialog(this, "Failed to connect to server");
    }
    
    public void setRules(boolean open, boolean random, boolean same, boolean plus, boolean combo) {
        game.setRules(open, random, same, plus, combo);
        game.start();
        connection.sendRules(open, random, same, plus, combo);
        pnlRules.setVisible(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private frames.pnlCardSelect pnlCardSelect2;
    private frames.LoginPanel pnlLogin;
    private frames.RulesPanel pnlRules;
    // End of variables declaration//GEN-END:variables
}
